// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Villa.API.Data;

#nullable disable

namespace Villa.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230316110453_SeedVillaTable")]
    partial class SeedVillaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Villa.API.Models.VillaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "This 6-storey townhouse is located in Nanshan District, Shenzhen, surrounded by lakes and dense forests. It enables owners to take a journey to Shenzhen Bay and the South China Sea right from their front door.\r\n\r\nDrawing on various artworks of both Chinese and foreign masters of art, the designers mix Eastern elegance or Western aesthetics, Chinese charm or French classics, colourful ink or black and white minimalism, to infuse the space with different artistic spirits, making the space not only skillfully crafted but also rhythmical.The butterfly art installation is motivated by artist Zhou Li's \"Metamorphosis,\" which uses traditional weaving techniques to produce flexible wire in a form that is light and dynamic, like a butterfly escaping from its cocoon and illustrating the tension of rebirth.",
                            ImageUrl = "https://amazingarchitecture.com/storage/3816/responsive-images/1-shenzhen_lakeside_villa_ace_design___media_library_original_1344_756.jpg",
                            Name = "Shenzhen Lakeside Villa",
                            Occupancy = 30,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Deep Villa speaks of modernity and globalization, demonstrating the absorption of modern influences from the West ,the more recent processes of globalization but also their sensitivity to the physical environment, the social context and the aspirations of the urban classes.",
                            ImageUrl = "https://amazingarchitecture.com/storage/711/responsive-images/Deep-Villa-Atrey-and-Associates-New-Delhi-ndia-Amazing-Architecture-House___media_library_original_1386_924.jpg",
                            Name = "Deep Villa",
                            Occupancy = 60,
                            Rate = 800.0,
                            Sqft = 464,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "The main idea for this beautiful villa project was to create a peaceful, luxury, modern and bright environment, where each space is cozy and tranquil. The rooms are very airy and full of light all day long, while once the sun goes down, each area gets its relaxing and romantic feel.",
                            ImageUrl = "https://amazingarchitecture.com/storage/3411/responsive-images/1-dubai_hills_villa_shawa_architecture___media_library_original_1344_756.jpg",
                            Name = "Iconic Dubai Hills Villa",
                            Occupancy = 30,
                            Rate = 500.0,
                            Sqft = 164,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Various elements from architecture through the ages and cultures have been an inspiration for the design of this villa. The entrance is an inspiration from the “GATES OF HEAVEN “ in Bali and the foyer is an influence from Geoffrey Bawa’s houses in Sri Lanka with a green space creating a completely natural setting by bringing natural light into the foyer through a semi-covered shade above the green pocket. The pitched roof pavilion gives the user an experience of Balinese architecture. This home is an attempt to explore the blend of traditional and contemporary interiors.",
                            ImageUrl = "https://amazingarchitecture.com/storage/2989/responsive-images/villa_79_ace_associates_karamsad_india___media_library_original_1344_756.jpg",
                            Name = "Villa 79",
                            Occupancy = 79,
                            Rate = 1200.0,
                            Sqft = 1011,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
